In [1]:
#H01T02
#funktio vertaa kahta taulukkoa ja jos
#ekassa on pienempi alkio, korvaa sen -1.llä.
#lopuksi palautetaan alkioittainen summa

In [2]:
def vertaa(luvut1,luvut2):
    import numpy as np
    
    #tehdään np-arrayt ja työskennellään niillä
    luvut1_np = np.array(luvut1)
    luvut2_np = np.array(luvut2)
    
    #alkioittainen vertailu ja
    #pienemmän arvon korvaaminen -1:llä.
    #"boolean-suodatus"
    pk = luvut1_np < luvut2_np
    luvut1_np[pk] = -1
    
    #alkioittainen summa
    tulos = np.add(luvut1_np,luvut2_np)
    
    return tulos

In [3]:
#syötteet
luvut1 = [[12, 2, 4], [5, 1, 2], [9, 3, 45]]
luvut2 = [[11, 9, 32], [2, 3, 1], [0, 3, 10]]

print(vertaa(luvut1,luvut2))

[[23  8 31]
 [ 7  2  3]
 [ 9  6 55]]
